### ISSUE TITLE
Module parse failed on .png file in version 1.1.0

### ISSUE THREAD

**Issue by mzakrze** [nhnent/tui.editor#152]
## Version
npm: 5.0.0
node: 8.0.0
tui-editor: 1.1.0
react: 15.6.2

## Test Environment

Chrome, Linux

## Current Behavior

I'm importing styles like:
```js
import 'tui-editor/dist/tui-editor.css';
```
via webpack.

Running: npm start causes: 

```js
ERROR in ./~/tui-editor/dist/tui-editor-2x.png
Module parse failed: /home/xxxxx/impl/frontend/node_modules/tui-editor/dist/tui-editor-2x.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/home/xxxxx/impl/frontend/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/xxxxx/impl/frontend/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/xxxxx/impl/frontend/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/xxxxx/impl/frontend/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/home/xxxxx/impl/frontend/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/home/xxxxx/impl/frontend/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/xxxxx/impl/frontend/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/home/xxxxx/impl/frontend/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/home/xxxxx/impl/frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/xxxxx/impl/frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/xxxxx/impl/frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/xxxxx/impl/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/xxxxx/impl/frontend/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:490:3)
 @ ./~/css-loader?importLoaders=1!./~/tui-editor/dist/tui-editor.css 7:18845-18875
```

Changing tui-editor@1.1.0 to 1.0.0 fixes problem

## Expected Behavior

npm start causes not errors and editor is pretty and responsive

**Comment by vpapadopou** [comment]
You need to use `extract-text-webpack-plugin`
https://github.com/webpack-contrib/extract-text-webpack-plugin

and set `publicPath: '/'`
