### ISSUE TITLE
scrollIntoView 이 정의되어 있지 않다는 오류.

### ISSUE THREAD

**Issue by urstory** [nhnent/tui.editor#156]
jQuery.Deferred exception: Cannot read property 'scrollIntoView' of undefined TypeError: Cannot read property 'scrollIntoView' of undefined
    at PopupCodeBlockLanguages._activateButtonByIndex (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:21518:27)
    at PopupCodeBlockLanguages._initDOM (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:21434:12)
    at PopupCodeBlockLanguages.LayerPopup (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:1039:11)
    at new PopupCodeBlockLanguages (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:21392:131)
    at DefaultUI._initPopupCodeBlockLanguages (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:18168:25)
    at DefaultUI._init (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:18038:12)
    at new DefaultUI (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:17968:10)
    at new ToastUIEditor (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:9552:35)
    at Function.factory (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:10287:21)
    at w.fn.init._jquery2.default.fn.tuiEditor (http://localhost:8080/static/node_modules/tui-editor/dist/tui-editor-Editor.js:9165:25) undefined
w.Deferred.exceptionHook @ jquery.js:3818
c @ jquery.js:3606
setTimeout (async)
(anonymous) @ jquery.js:3640
u @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
u @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
_ @ jquery.js:3888
jquery.js:3827 Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined
    at PopupCodeBlockLanguages._activateButtonByIndex (tui-editor-Editor.js:21518)
    at PopupCodeBlockLanguages._initDOM (tui-editor-Editor.js:21434)
    at PopupCodeBlockLanguages.LayerPopup (tui-editor-Editor.js:1039)
    at new PopupCodeBlockLanguages (tui-editor-Editor.js:21392)
    at DefaultUI._initPopupCodeBlockLanguages (tui-editor-Editor.js:18168)
    at DefaultUI._init (tui-editor-Editor.js:18038)
    at new DefaultUI (tui-editor-Editor.js:17968)
    at new ToastUIEditor (tui-editor-Editor.js:9552)
    at Function.factory (tui-editor-Editor.js:10287)
    at w.fn.init._jquery2.default.fn.tuiEditor (tui-editor-Editor.js:9165)

위와 같이 오류가 발생하는데요. 아래와 같은 내용처럼 codeBlockLanguages 를 추가하니 오류가 발생하지 않습니다.

https://stackoverflow.com/questions/48786000/difficulties-in-integrating-tui-editor-1-0-3

**Comment by urstory** [comment]
npm install --save tui-editor
으로 코드를 받아온 내용을 사용할 경우에는 위와 같은 오류가 발생하고

bower를 통해서 가지고 왔을 경우에는 오류가 발생하지 않네요.

**Comment by seulgiseong** [comment]
저도 같은 현상이 나타나서 확인해봤는데 코드블럭 언어 정보가 없어서 나타난 현상인듯 합니다.
tui-editor를 사용하면 하이라이팅 가능한 모든 언어를 불러오고 있어서 webpack 설정에서 highlight.js에 alias를 걸었습니다.

```javascript
resolve: {
        alias: {
            'highlight.js$': require.resolve('highlight.js/lib/highlight')
        }
    },
```

이렇게 하면 하이라이팅 언어 없어 highlight.js를 불러오고 추후에 언어를 등록해서 하이라이팅이 가능해집니다. 
tui-editor 초기화 단계에서 언어 정보가 없어 코드블럭 관련 버튼이 하나도 만들어지지 않은 상태에서 scrollIntoView가 동작하는듯 합니다.

하이라이팅에서 모든 언어가 로딩되면 번들 파일의 크기가 커지기도 하고, 모든 언어가 필요하지 않기 때문에 필요한 하이라이팅 언어만 불러올 수 있는 옵션이 있으면 좋을것 같습니다.

**Comment by urstory** [comment]
👍

**Comment by einverne** [comment]
meet the same problem.

**Comment by sohee-lee7** [comment]
This issue is resolved so close it.
