### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Connum** [nhnent/tui.editor#283]
## Version
master branch

## Test Environment
not applicable

## Current Behavior

I grabbed the current master in order to build it, because I need a stand-alone version and would like to use the new "tui-editor-Editor-deps.js" instead of having to add all the dependencies manually.

After `npm install` I tried `npm run build` and `npm run-script build` - but I always get these errors:

```> tui-editor@1.2.6 build D:\xampp\htdocs\tui.editor
> cross-env webpack && webpack -p

'webpack' is not recognized as an internal or external command,
operable program or batch file.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at notFoundError (C:\Users\xx\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\xx\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\xx\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tui-editor@1.2.6 build: `cross-env webpack && webpack -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tui-editor@1.2.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I installed cross-env globally, because that's what helped with another package with a similiar problem, but to no avail.

## Expected Behavior

build process works

**Comment by kyuwoo-choi** [comment]
you need the webpack installed as a dependency or globally.
